apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260621-190213-zky15c38qrvj-service
spec:
  selector:
    app: enterprise-system-20260621-190213-zky15c38qrvj
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
